Repository Kernel360/F2-omocha-FE, pull requests merged in 2024-09, with the labels that each got.

#11 [FEAT] 공용 레이아웃 구현 및 Breadcrumb 구현
  .eslintrc.json
  next.config.mjs
  package-lock.json
  src/app/basicauction/[id]/page.tsx
  src/app/page.module.css
  src/app/page.tsx
  src/components/AuctionCard/AuctionCard.css.ts
  src/components/AuctionCard/index.tsx
  src/components/Breadcrumb/Breadcrumb.css.ts
  src/components/Breadcrumb/index.tsx
  src/components/ItemCard/ItemCard.css.ts
  src/components/ItemCard/index.tsx
  src/components/ListLayout/ListLayout.css.ts
  src/components/ListLayout/index.tsx
  src/stories/ListLayout.stories.ts
Labels: 🎨 UI

#16 [FEAT] 마이페이지 공용 레이아웃 구현
  src/app/globals.css.ts
  src/app/layout.tsx
  src/app/mypage/Layout.css.ts
  src/app/mypage/heart/page.tsx
  src/app/mypage/keyword/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/mypage/record/page.tsx
  src/assets/svg/profile.svg
  src/components/Footer/Footer.css.ts
  src/components/Header/Header.css.ts
  src/static/category.ts
Labels: 🎨 UI

#22 [FEAT] 회원가입 구현(api X)
  src/app/globals.css.ts
  src/app/join/Join.css.ts
  src/app/join/page.tsx
  src/app/login/Login.css.ts
  src/app/login/page.tsx
  src/assets/svg/check.svg
  src/assets/svg/goggle.svg
  src/components/Footer/Footer.css.ts
  src/components/ListLayout/ListLayout.css.ts
Labels: ✨ Feature, 🎨 UI

#23 [FEAT] 공용 타이머 훅 구현 및 적용
  src/components/AuctionInfo/AuctionCountdown.css.ts
  src/components/AuctionInfo/AuctionCountdown.tsx
  src/components/AuctionInfo/AuctionInfo.css.ts
  src/components/AuctionInfo/index.tsx
  src/hooks/useCountdownTimer.ts
Labels: ✨ Feature, 🎨 UI

#33 [CHORE] import 순서 변경 lint 추가
  .eslintrc.json
  src/app/create/basicauction/page.tsx
  src/app/create/page.tsx
  src/app/join/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/mypage/layout.tsx
  src/components/AuctionCard/index.tsx
  src/components/AuctionInfo/AuctionCountdown.tsx
  src/components/AuctionInfo/index.tsx
  src/components/Breadcrumb/index.tsx
  src/components/Footer/index.tsx
  src/components/Header/index.tsx
  src/components/Modal/index.tsx
  src/components/TabsLayout/index.tsx
  src/stories/AuctionCard.stories.ts
  src/stories/AuctionInfo.stories.ts
  src/stories/ItemCard.stories.ts
  src/stories/ListLayout.stories.ts
  src/stories/Modal.stories.tsx
  src/stories/TabsLayout.stories.tsx
Labels: ⚙ Setting
