Repository Kernel360/F2-omocha-FE, pull requests merged in 2024-10, with the labels that each got.

#34 [FEAT] 메인 알림 페이지 레이아웃 구성
  src/app/create/basicauction/page.tsx
  src/app/create/page.tsx
  src/app/layout.tsx
  src/app/mypage/layout.tsx
  src/assets/svg/x.svg
  src/components/Footer/index.tsx
  src/components/Header/Header.css.ts
  src/components/Header/components/Alarm/Alarm.css.ts
  src/components/Header/components/Alarm/index.tsx
  src/components/Header/index.tsx
  src/components/Modal/Modal.css.ts
  src/components/Modal/index.tsx
  src/components/Portal/index.tsx
  src/components/SlideSideNav/SlideSideNav.css.ts
  src/components/SlideSideNav/index.tsx
  src/hooks/useBooleanState.ts
  src/hooks/useOnClickOutside.ts
  src/static/category.ts
Labels: ✨ Feature, 🎨 UI

#37 [FEAT] 공용 모달 컴포넌트 구조 변경
  package-lock.json
  package.json
  src/app/create/Create.css.ts
  src/app/create/page.tsx
  src/components/Modal/Modal.css.ts
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalFooter.tsx
  src/components/Modal/ModalHeaderFooter.tsx
  src/components/Modal/index.tsx
  src/stories/Modal.stories.tsx
Labels: 🎨 UI, 🔨 Refactor

#38 [FEAT] 경매 list, detail page api 연동
  next.config.mjs
  package-lock.json
  package.json
  src/apis/queryFunctions/apiClient.ts
  src/apis/queryFunctions/basicAuctionQueryFn.ts
  src/apis/queryHooks/basicAuction/useDeleteBasicAuction.ts
  src/apis/queryHooks/basicAuction/useGetBasicAuction.ts
  src/apis/queryHooks/basicAuction/useGetBasicAuctionList.ts
  src/apis/types/Auction.ts
  src/app/basicauction/[id]/BasicAuctionDetailPage.css.ts
  src/app/basicauction/[id]/BasicAuctionInfo.tsx
  src/app/basicauction/[id]/page.tsx
  src/app/basicauction/components/searchbar.tsx
  src/app/basicauction/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/components/AuctionCard/index.tsx
  src/components/AuctionInfo/AuctionCountdown.tsx
  src/components/AuctionInfo/AuctionInfo.css.ts
  src/components/AuctionInfo/index.tsx
  src/hooks/useCountdownTimer.ts
  src/utils/convertQueryParamsObjectToString.ts
Labels: ✨ Feature, 📬 API

#39 [FEAT] 경매 업로드 api 연동
  package-lock.json
  package.json
  src/apis/queryFunctions/Auth.ts
  src/apis/queryFunctions/apiClient.ts
  src/apis/queryFunctions/basicAuction.ts
  src/apis/queryHooks/basicAuction/useGetBasicAuction.ts
  src/apis/queryHooks/basicAuction/useGetBasicAuctionList.ts
  src/apis/queryHooks/basicAuction/usePostBasicAuction.ts
  src/apis/queryHooks/useAuth/usePostLogin.ts
  src/apis/types/Auth.ts
  src/apis/types/basicAuction.ts
  src/app/basicauction/[id]/page.tsx
  src/app/create/basicauction/Basicauction.css.ts
  src/app/create/basicauction/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/utils/formatDate.ts
  src/utils/sha256.ts
Labels: ✨ Feature, 📬 API

#43 [FEAT] 메인 페이지 수정, 경매 업로드 415 에러 수정
  src/apis/queryFunctions/basicAuction.ts
  src/apis/queryHooks/basicAuction/usePostBasicAuction.ts
  src/apis/types/basicAuction.ts
  src/app/basicauction/basicauction.tsx
  src/app/create/basicauction/Basicauction.css.ts
  src/app/create/basicauction/page.tsx
  src/app/howto/page.tsx
  src/app/page.css.ts
  src/app/page.module.css
  src/app/page.tsx
  src/assets/svg/arrow-right.svg
  src/components/AuctionList/AuctionList.css.ts
  src/components/AuctionList/index.tsx
  src/utils/convertQueryParamsObjectToString.ts
  src/utils/formatDate.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 UI

#48 [FIX] useCountdownTimer 서버 시간 오차 이슈 해결
  src/apis/types/basicAuction.ts
  src/app/basicauction/basicauction.tsx
  src/app/page.tsx
  src/components/AuctionInfo/AuctionCountdown.tsx
  src/hooks/useCountdownTimer.ts
  src/utils/calcRemainingTime.ts
Labels: 🐞 BugFix, 🔨 Refactor

#49 [FEAT] 입찰, 입찰 목록 기능 구현 및 api 제네릭 타입 수정
  src/apis/queryFunctions/Auth.ts
  src/apis/queryFunctions/basicAuction.ts
  src/apis/queryHooks/basicAuction/useGetBasicAuctionBidList.ts
  src/apis/queryHooks/basicAuction/usePostBasicAuction.ts
  src/apis/queryHooks/basicAuction/usePostBasicAuctionBid.ts
  src/apis/queryHooks/useAuth/usePostLogin.ts
  src/apis/queryHooks/useAuth/usePostRegister.ts
  src/apis/types/basicAuction.ts
  src/apis/types/common.ts
  src/app/basicauction/[id]/BasicAuctionInfo.tsx
  src/app/basicauction/basicauction.tsx
  src/app/page.tsx
  src/components/AuctionCard/AuctionCard.css.ts
  src/components/AuctionCard/index.tsx
  src/components/AuctionInfo/AuctionBidListModal.css.ts
  src/components/AuctionInfo/AuctionBidListModal.tsx
  src/components/AuctionInfo/AuctionInfo.css.ts
  src/components/AuctionInfo/index.tsx
  src/components/AuctionList/index.tsx
  src/components/Header/components/HeaderActionItem.tsx
  src/components/Header/components/HeaderLinkItem.tsx
  src/components/Header/index.tsx
  src/components/Modal/Modal.css.ts
  src/static/category.ts
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#53 [FEAT] 경매 list detail 챙기기
  src/apis/queryFunctions/basicAuction.ts
  src/apis/types/basicAuction.ts
  src/app/basicauction/Basicauction.css.ts
  src/app/basicauction/basicauction.tsx
  src/app/basicauction/components/auctiondropdown.tsx
  src/app/basicauction/components/searchbar.tsx
  src/components/Dropdown/index.tsx
  src/components/SlideSideNav/index.tsx
  src/hooks/useOnClickOutside.ts
  src/hooks/useSetSearchParam.ts
  src/static/queryParam.ts
  src/static/sort.ts
Labels: ✨ Feature, 🔨 Refactor

#54 [FEAT] 입찰 기능 validation 추가
  src/apis/queryHooks/basicAuction/usePostBasicAuctionBid.ts
  src/app/basicauction/[id]/BasicAuctionInfo.tsx
  src/components/AuctionInfo/AuctionBidConfirmModal.tsx
  src/components/AuctionInfo/AuctionInfo.css.ts
  src/components/AuctionInfo/index.tsx
  src/hooks/useCountdownTimer.ts
Labels: ✨ Feature, 🎨 UI

#63 [FEAT] 내 정보 api 연동
  .eslintrc.json
  src/apis/queryFunctions/User.ts
  src/apis/queryHooks/useAuth/usePostLogin.ts
  src/apis/types/User.ts
  src/apis/types/basicAuction.ts
  src/app/basicauction/[id]/BasicAuctionInfo.tsx
  src/app/mypage/Layout.css.ts
  src/app/mypage/heart/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/profile/page.tsx
  src/components/AuctionInfo/hooks/useHandleBidPrice.ts
  src/components/AuctionInfo/hooks/usePermissionBidPrice.ts
  src/components/AuctionInfo/index.tsx
  src/store/useUserStore.ts
Labels: ✨ Feature, 📬 API

#85 [REFACTOR] 채팅 소켓 통신 리팩토링
  src/apis/queryFunctions/chat.ts
  src/apis/queryHooks/chat/useGetLastChat.ts
  src/app/layout.tsx
  src/components/ChatModal/ChatModal.css.ts
  src/components/ChatModal/ChatModal.tsx
  src/components/Chatting/Chatting.css.ts
  src/components/Chatting/ChattingIconButton.css.ts
  src/components/Chatting/ChattingIconButton.tsx
  src/components/Chatting/ChattingList.tsx
  src/components/Chatting/ChattingUnit.tsx
  src/components/Chatting/Chattingroom.tsx
  src/components/Chatting/hooks/useChatSocket.ts
  src/components/ChattingPopover/ChattingPopover.css.ts
  src/components/ChattingPopover/index.tsx
  src/components/Header/components/Chatting/Chattingroom.tsx
  src/hooks/useSocket.ts
Labels: 🔨 Refactor

#92 [FEAT] 텍스트 에디터 추가
  .github/workflows/BUNDLE_SIZE.yml
  next.config.mjs
  package-lock.json
  package.json
  src/app/basicauction/[id]/BasicAuctionInfoContent.tsx
  src/app/create/basicauction/Basicauction.css.ts
  src/app/create/basicauction/components/contentrequired.tsx
  src/app/create/basicauction/page.tsx
  src/app/create/basicauction/types/InputTypes.ts
  src/assets/svg/logo.svg
  src/assets/svg/text-editor/align-center.svg
  src/assets/svg/text-editor/align-justify.svg
  src/assets/svg/text-editor/align-left.svg
  src/assets/svg/text-editor/align-right.svg
  src/assets/svg/text-editor/bold.svg
  src/assets/svg/text-editor/code.svg
  src/assets/svg/text-editor/heading-1.svg
  src/assets/svg/text-editor/heading-2.svg
  src/assets/svg/text-editor/italic.svg
  src/assets/svg/text-editor/list-bullet.svg
  src/assets/svg/text-editor/list-number.svg
  src/assets/svg/text-editor/quote.svg
  src/assets/svg/text-editor/underline.svg
  src/components/AuctionInfo/index.tsx
  src/components/TextEditor/BlockButton.tsx
  src/components/TextEditor/Elements.tsx
  src/components/TextEditor/Leaf.tsx
  src/components/TextEditor/MarkButton.tsx
  src/components/TextEditor/TextEditor.css.ts
  src/components/TextEditor/hooks/useEditorShortcuts.ts
  src/static/icon.tsx
  src/utils/convertSlateToHTML.ts
  src/utils/countContentText.ts
  src/utils/customEditor.ts
Labels: ✨ Feature

#90 [FEAT] 채팅 추가 기능 구현
  src/apis/queryHooks/chat/useGetLastChat.ts
  src/components/Chatting/Chatting.css.ts
  src/components/Chatting/Chattingroom.tsx
  src/components/Chatting/hooks/useChatSocket.ts
Labels: ✨ Feature
