Repository Kernel360/F2-omocha-FE, pull requests merged in 2024-11, with the labels that each got.

#97 [FEAT] 공용 Input, button 구현 및 게시글 업로드 페이지 적용
  src/app/create/Basicauction.css.ts
  src/app/create/Create.css.ts
  src/app/create/basicauction/page.tsx
  src/app/create/components/contentrequired.tsx
  src/app/create/page.tsx
  src/app/create/types/InputTypes.ts
  src/components/AuctionCard/AuctionCard.css.ts
  src/components/CommonButton/CommonButton.css.ts
  src/components/CommonButton/index.tsx
  src/components/CommonInput/CommonInput.css.ts
  src/components/CommonInput/index.tsx
  src/components/Footer/Footer.css.ts
  src/components/Header/Header.css.ts
  src/components/SpecialSection/SpecialSection.css.ts
  src/styles/color.ts
Labels: ✨ Feature, 🎨 UI, 🔨 Refactor

#99 [FEAT] 경매 리스트 페이지 스켈레톤 UI 추가
  src/apis/queryHooks/basicAuction/useGetBasicAuctionList.ts
  src/app/basicauction/Basicauction.css.ts
  src/app/basicauction/basicauction.tsx
  src/app/basicauction/components/AuctionDropDown.css.ts
  src/app/basicauction/components/LeftSection.css.ts
  src/app/basicauction/components/SearchBar.css.ts
  src/app/basicauction/components/auctiondropdown.tsx
  src/app/basicauction/components/checkbox.tsx
  src/app/basicauction/components/leftsection.tsx
  src/app/basicauction/components/searchbar.tsx
  src/app/basicauction/page.tsx
  src/app/globals.css.ts
  src/app/mypage/keyword/page.tsx
  src/assets/svg/delete.svg
  src/components/AuctionCard/AuctionCard.css.ts
  src/components/BasicAuctionClientPage/BasicAuctionClientPage.css.ts
  src/components/BasicAuctionClientPage/index.tsx
  src/components/DeferredComponent/index.tsx
  src/components/Dropdown/Dropdown.css.ts
  src/components/Dropdown/index.tsx
  src/components/MaxLayout/MaxLayout.css.ts
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalFooter.tsx
  src/components/Modal/ModalHeaderFooter.tsx
  src/components/SkeletonUI/AuctionListSkeletonUI.css.ts
  src/components/SkeletonUI/AuctionListSkeletonUI.tsx
  src/components/SkeletonUI/components/SkeletonCard.tsx
  src/components/SkeletonUI/components/SkeletonCircle.tsx
  src/components/SkeletonUI/components/SkeletonText.tsx
  src/components/SkeletonUI/components/SkeletonUI.css.ts
  src/styles/typo.ts
Labels: ✨ Feature, 🎨 UI, 🔨 Refactor

#107 [FEAT] 이미지 업로드 추가, 텍스트 에디터 이슈 해결
  package-lock.json
  package.json
  src/app/basicauction/[id]/BasicAuctionInfoContent.css.ts
  src/app/basicauction/components/LeftSection.css.ts
  src/app/create/Basicauction.css.ts
  src/app/create/components/contentrequired.tsx
  src/app/create/components/imagerequired.tsx
  src/app/create/page.tsx
  src/app/create/types/InputTypes.ts
  src/app/create/utils/createValidation.ts
  src/assets/svg/text-editor/align-center.svg
  src/assets/svg/text-editor/align-justify.svg
  src/assets/svg/text-editor/align-left.svg
  src/assets/svg/text-editor/align-right.svg
  src/assets/svg/text-editor/bold.svg
  src/assets/svg/text-editor/code.svg
  src/assets/svg/text-editor/heading-1.svg
  src/assets/svg/text-editor/heading-2.svg
  src/assets/svg/text-editor/italic.svg
  src/assets/svg/text-editor/list-bullet.svg
  src/assets/svg/text-editor/list-number.svg
  src/assets/svg/text-editor/quote.svg
  src/assets/svg/text-editor/underline.svg
  src/components/Chatting/ChattingIconButton.css.ts
  src/components/TextEditor/Elements.tsx
  src/components/TextEditor/ImageTooltip.tsx
  src/components/TextEditor/Leaf.tsx
  src/components/TextEditor/TextEditor.css.ts
  src/components/TextEditor/hooks/useImage.ts
  src/components/TextEditor/hooks/useWithImages.ts
  src/static/textEditorIcon.tsx
  src/utils/convertSlateToHTML.ts
  src/utils/convertSlateToHTML.tsx
  src/utils/countContentText.ts
Labels: 🐞 BugFix, ✨ Feature

#110 [FEAT] 카테고리 구현
  package-lock.json
  package.json
  src/apis/queryFunctions/Auth.ts
  src/apis/queryFunctions/User.ts
  src/apis/queryFunctions/apiClient.ts
  src/apis/queryFunctions/basicAuction.ts
  src/apis/queryFunctions/category.ts
  src/apis/queryFunctions/chat.ts
  src/apis/queryHooks/category/useGetCategory.ts
  src/apis/types/User.ts
  src/apis/types/basicAuction.ts
  src/apis/types/category.ts
  src/apis/types/chat.ts
  src/app/basicauction/Basicauction.css.ts
  src/app/basicauction/[id]/BasicAuctionInfo.tsx
  src/app/basicauction/[id]/QnAInputSection.tsx
  src/app/basicauction/components/LeftSection.css.ts
  src/app/basicauction/components/leftsection.tsx
  src/app/basicauction/page.tsx
  src/app/create/page.tsx
  src/app/globals.css.ts
  src/app/join/Join.css.ts
  src/app/layout.tsx
  src/app/login/Login.css.ts
  src/app/login/page.tsx
  src/app/mypage/heart/components/basicheart.tsx
  src/app/mypage/profile/Profile.css.ts
  src/components/AuctionCard/index.tsx
  src/components/AuctionCategory/AuctionCategory.css.ts
  src/components/AuctionCategory/CategoryUnit.css.ts
  src/components/AuctionCategory/CategoryUnit.tsx
  src/components/AuctionCategory/index.tsx
  src/components/AuctionInfo/hooks/useHandleBidPrice.ts
  src/components/AuctionInfo/index.tsx
  src/components/AuctionList/index.tsx
  src/components/BasicAuctionClientPage/index.tsx
  src/components/CommonInput/index.tsx
  src/components/Dropdown/index.tsx
  src/components/Header/Header.css.ts
  src/components/Header/components/CategoryHeader/CategoryHeader.css.ts
  src/components/Header/components/CategoryHeader/index.tsx
  src/components/Header/components/UserHeader/UserHeader.css.ts
  src/components/Header/components/UserHeader/index.tsx
  src/components/Header/index.tsx
  src/components/MaxLayout/MaxLayout.css.ts
  src/components/SpecialSection/index.tsx
  src/components/ToastUI/ToastUI.css.ts
  src/mocks/data/category.ts
  src/static/category.ts
Labels: 🎨 UI, 📬 API, 🔨 Refactor

#115 [FEAT] 카테고리 추가
  package-lock.json
  package.json
  src/apis/queryHooks/category/useGetCategory.ts
  src/apis/types/category.ts
  src/app/basicauction/components/leftsection.tsx
  src/app/create/Basicauction.css.ts
  src/app/create/components/CategoryTree.css.ts
  src/app/create/components/CategoryTree.tsx
  src/app/create/components/contentrequired.tsx
  src/app/create/components/enddaterequired.tsx
  src/app/create/components/imagerequired.tsx
  src/app/create/components/namerequired.tsx
  src/app/create/components/typepricerequired.tsx
  src/app/create/page.tsx
  src/app/create/types/InputTypes.ts
  src/app/create/utils/createValidation.ts
  src/app/globals.css.ts
  src/app/mypage/heart/components/basicheart.tsx
  src/components/AuctionCard/index.tsx
  src/components/AuctionList/index.tsx
  src/components/BasicAuctionClientPage/index.tsx
  src/components/CommonInput/index.tsx
  src/components/Header/index.tsx
  src/mocks/data/category.ts
Labels: ✨ Feature, 🎨 UI, 📬 API

#121 [FEAT] 채팅 api, QnA api 반영
  next.config.mjs
  src/apis/queryFunctions/chat.ts
  src/apis/queryHooks/basicAuction/useGetBasicAuctionQnAList.ts
  src/apis/queryHooks/chat/useGetLastChat.ts
  src/apis/types/basicAuction.ts
  src/apis/types/chat.ts
  src/app/basicauction/[id]/BasicAuctionInfoQnA.css.ts
  src/app/basicauction/[id]/BasicAuctionInfoQnA.tsx
  src/app/basicauction/[id]/QnAUnit.tsx
  src/components/AuctionInfo/AuctionBidListModal.tsx
  src/components/Chatting/Chatting.css.ts
  src/components/Chatting/ChattingList.tsx
  src/components/Chatting/ChattingUnit.tsx
  src/components/Chatting/Chattingroom.tsx
  src/components/Chatting/hooks/useChatSocket.ts
Labels: 📬 API

#127 [REFACTOR] 헤더, 푸터, 메인 페이지 반응형 수정
  src/app/basicauction/components/LeftSection.css.ts
  src/app/globals.css.ts
  src/app/join/Join.css.ts
  src/app/layout.tsx
  src/app/login/Login.css.ts
  src/components/Footer/Footer.css.ts
  src/components/Header/components/CategoryHeader/CategoryHeader.css.ts
  src/components/HeaderSection/components/Alarm/Alarm.css.ts
  src/components/HeaderSection/components/Alarm/index.tsx
  src/components/HeaderSection/components/CategoryHeader/CategoryHeader.css.ts
  src/components/HeaderSection/components/CategoryHeader/index.tsx
  src/components/HeaderSection/components/Header/Header.css.ts
  src/components/HeaderSection/components/Header/Header.tsx
  src/components/HeaderSection/components/MobileHeader/MobileHeader.css.ts
  src/components/HeaderSection/components/MobileHeader/MobileHeader.tsx
  src/components/HeaderSection/components/MobileUserHeader/MobileUserHeader.css.ts
  src/components/HeaderSection/components/MobileUserHeader/index.tsx
  src/components/HeaderSection/components/UserHeader/UserHeader.css.ts
  src/components/HeaderSection/components/UserHeader/index.tsx
  src/components/HeaderSection/index.tsx
  src/components/MainCarousel/MainCarousel.css.ts
  src/components/SpecialSection/SpecialSection.css.ts
  src/components/SpecialSection/index.tsx
  src/static/category.ts
  src/styles/layout.ts
Labels: ✨ Feature, 🎨 UI, 🔨 Refactor

#125 [FEAT] 메인페이지 페이지네이션 추가
  package-lock.json
  package.json
  src/apis/queryFunctions/User.ts
  src/apis/queryHooks/User/useGetAuctionLikeList.ts
  src/apis/queryHooks/basicAuction/useGetBasicAuctionList.ts
  src/apis/types/basicAuction.ts
  src/app/basicauction/Basicauction.css.ts
  src/app/basicauction/[id]/page.tsx
  src/app/basicauction/basicauction.tsx
  src/app/basicauction/components/checkbox.tsx
  src/app/basicauction/components/leftsection.tsx
  src/app/basicauction/page.tsx
  src/app/layout.tsx
  src/app/login/Login.css.ts
  src/app/login/page.tsx
  src/app/mypage/heart/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/record/components/BasicBidAuction.tsx
  src/app/mypage/record/components/basicsold.tsx
  src/assets/png/image-off.png
  src/components/AuctionCard/index.tsx
  src/components/AuctionCategory/AuctionCategory.css.ts
  src/components/AuctionCategory/CategoryUnit.tsx
  src/components/AuctionCategory/index.tsx
  src/components/BasicAuctionClientPage/BasicAuctionClientPage.css.ts
  src/components/BasicAuctionClientPage/index.tsx
  src/components/CommonImage/CommonImage.css.ts
  src/components/CommonImage/index.tsx
  src/components/HeaderSection/components/CategoryHeader/index.tsx
  src/components/HeaderSection/components/UserHeader/index.tsx
  src/components/NavigationEvents/index.tsx
  src/components/Pagination/Pagination.css.ts
  src/components/Pagination/index.tsx
  src/components/SkeletonUI/AuctionListSkeletonUI.tsx
  src/hooks/usePrefetchQueryWithCookie.ts
  src/hooks/useSetSearchParam.ts
  src/utils/convertQueryParamsObjectToString.ts
  src/utils/filteredParams.ts
Labels: ✨ Feature

#131 [REFACTOR] 상품 디테일 페이지 반응형 구현
  src/app/basicauction/[id]/QnAInputSection.css.ts
  src/app/basicauction/[id]/QnAInputSection.tsx
  src/app/basicauction/[id]/QnAUnit.css.ts
  src/app/basicauction/[id]/page.tsx
  src/app/mypage/keyword/page.tsx
  src/app/page.tsx
  src/components/AuctionCategory/CategoryUnit.css.ts
  src/components/AuctionImageInfo/AuctionImageInfo.css.ts
  src/components/AuctionImageInfo/index.tsx
  src/components/AuctionInfo/AuctionCountdown.tsx
  src/components/AuctionInfo/AuctionInstantBuyConfirmModal.tsx
  src/components/Modal/Modal.css.ts
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalFooter.tsx
  src/components/Modal/ModalHeaderFooter.tsx
  src/hooks/useCountdownTimer.ts
Labels: 🎨 UI, 🔨 Refactor

#142 [REFACTOR] 회원가입, 로그인페이지 QA 수정
  public/icon.ico
  src/apis/queryHooks/Auth/usePostLogin.ts
  src/apis/queryHooks/Auth/usePostLogout.ts
  src/apis/queryHooks/User/useGetUser.ts
  src/apis/types/User.ts
  src/app/basicauction/[id]/HaveToLoginNotiModal.tsx
  src/app/globals.css.ts
  src/app/join/Join.css.ts
  src/app/join/page.tsx
  src/app/join/utils/joinValidation.ts
  src/app/layout.tsx
  src/app/login/Login.css.ts
  src/app/mypage/Layout.css.ts
  src/app/mypage/heart/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/profile/components/ChangePassword.css.ts
  src/app/mypage/profile/components/changepassword.tsx
  src/app/mypage/record/components/BasicBid.css.ts
  src/app/mypage/record/components/BasicSold.css.ts
  src/app/page.tsx
  src/components/AuctionCard/index.tsx
  src/components/AuctionInfo/AuctionBidListModal.tsx
  src/components/AuctionList/index.tsx
  src/components/HeaderSection/components/MobileSlideNav/index.tsx
  src/components/HeaderSection/components/UserHeader/index.tsx
  src/components/MainCarousel/index.tsx
  src/components/MypageCategory/MypageCategory.css.ts
  src/components/MypageCategory/index.tsx
  src/components/MypageProfileClientPage/MypageProfileClientPage.css.ts
  src/components/MypageProfileClientPage/index.tsx
  src/components/MypageUserSection/MypageUserSection.css.ts
  src/components/MypageUserSection/components/ImageUploadModal.css.ts
  src/components/MypageUserSection/components/ImageUploadModal.tsx
  src/components/MypageUserSection/index.tsx
  src/components/SkeletonUI/components/SkeletonText.tsx
  src/components/SkeletonUI/components/SkeletonUI.css.ts
  src/components/SpecialSection/SpecialSection.css.ts
  src/components/TabsLayout/TabsLayout.css.ts
  src/hooks/usePrefetchQueriesWithCookie.ts
  src/hooks/usePrefetchQueryWithCookie.ts
  src/static/category.ts
  src/static/sort.ts
Labels: 🔨 Refactor

#147 [REFACTOR] 메인 페이지 수정
  src/components/AuctionCard/AuctionCard.css.ts
  src/components/Breadcrumb/Breadcrumb.css.ts
  src/components/Chatting/ChattingIconButton.css.ts
  src/components/MainCarousel/index.tsx
  src/components/MypageUserSection/components/ImageUploadModal.css.ts
  src/components/ScrollToTopButton/ScrollToTopButton.css.ts
  src/components/ScrollToTopButton/index.tsx
Labels: 🔨 Refactor
